# -*- coding: utf-8 -*-
"""dfa.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15HPM4-9ntEn0FntywJUI356cnY-pJ66u
"""

# DFA Simulation
# This DFA accepts binary strings ending with 1.

def dfa_simulation():

    # States
    states = ['q0', 'q1']

    # Alphabet
    alphabet = ['0', '1']

    # Transition table
    transitions = {
        'q0': {'0': 'q0', '1': 'q1'},
        'q1': {'0': 'q0', '1': 'q1'}
    }

    # Start state
    start_state = 'q0'

    # Final state
    final_states = {'q1'}

    print("===== DFA SIMULATION =====")

    # Input string
    input_string = input("Enter a binary string: ")

    # Initial state
    current_state = start_state

    print("\nDFA Processing:")
    print("Start state:", current_state)

    # Process input symbols
    for symbol in input_string:

        if symbol not in alphabet:
            print("Invalid input! Enter only 0 and 1.")
            return

        next_state = transitions[current_state][symbol]

        print(f"δ({current_state}, {symbol}) = {next_state}")

        current_state = next_state

    # Check final state
    print("\nFinal state:", current_state)

    if current_state in final_states:
        print("Result: STRING ACCEPTED")
    else:
        print("Result: STRING REJECTED")


# Execute DFA
dfa_simulation()

