# -*- coding: utf-8 -*-
"""Copy of dfa->nfa.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-6KqLbh4xQt_tcdJnQC5szNUnyWxxxFj
"""

# DFA to NFA Conversion
# A DFA is a special case of an NFA.
# Each DFA transition is converted into
# an NFA transition containing one destination state.

def dfa_to_nfa():

    print("===== DFA TO NFA CONVERSION =====")

    # States
    states = ['q0', 'q1']

    # Alphabet
    alphabet = ['0', '1']

    # DFA transition table
    dfa_transitions = {
        'q0': {
            '0': 'q0',
            '1': 'q1'
        },
        'q1': {
            '0': 'q0',
            '1': 'q1'
        }
    }

    # Start state
    start_state = 'q0'

    # Final state
    final_states = {'q1'}

    print("\n===== DFA TRANSITION TABLE =====")

    print("State\t0\t1")

    for state in states:
        print(
            f"{state}\t"
            f"{dfa_transitions[state]['0']}\t"
            f"{dfa_transitions[state]['1']}"
        )

    # Convert DFA transitions to NFA transitions
    nfa_transitions = {}

    for state in states:

        nfa_transitions[state] = {}

        for symbol in alphabet:

            destination = dfa_transitions[state][symbol]

            # NFA transition contains destination
            # inside a set
            nfa_transitions[state][symbol] = {destination}

    print("\n===== EQUIVALENT NFA TRANSITION TABLE =====")

    print("State\t0\t1")

    for state in states:

        print(
            f"{state}\t"
            f"{nfa_transitions[state]['0']}\t"
            f"{nfa_transitions[state]['1']}"
        )

    print("\n===== AUTOMATON DETAILS =====")
    print("States:", states)
    print("Alphabet:", alphabet)
    print("Start state:", start_state)
    print("Final states:", final_states)

    print("\nConversion completed successfully!")
    print("DFA and NFA are equivalent.")


# Execute conversion
dfa_to_nfa()