# -*- coding: utf-8 -*-
"""Copy of nfa.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-6KqLbh4xQt_tcdJnQC5szNUnyWxxxFj
"""

# NFA Simulation
# This NFA accepts binary strings ending with 01.

def nfa_simulation():

    # States
    states = ['q0', 'q1', 'q2']

    # Alphabet
    alphabet = ['0', '1']

    # NFA transition table
    transitions = {
        'q0': {
            '0': {'q0', 'q1'},
            '1': {'q0'}
        },
        'q1': {
            '0': set(),
            '1': {'q2'}
        },
        'q2': {
            '0': set(),
            '1': set()
        }
    }

    # Start state
    start_state = 'q0'

    # Final state
    final_states = {'q2'}

    print("===== NFA SIMULATION =====")

    # Input string
    input_string = input("Enter a binary string: ")

    # Initially only q0 is active
    current_states = {start_state}

    print("\nNFA Processing:")
    print("Initial state:", current_states)

    # Process every input symbol
    for symbol in input_string:

        if symbol not in alphabet:
            print("Invalid input! Enter only 0 and 1.")
            return

        next_states = set()

        # Find all possible next states
        for state in current_states:
            next_states.update(transitions[state][symbol])

        print(
            f"After reading '{symbol}': {next_states}"
        )

        current_states = next_states

        # If no possible path remains
        if not current_states:
            break

    print("\nFinal possible states:", current_states)

    # If any current state is a final state
    if current_states & final_states:
        print("Result: STRING ACCEPTED")
    else:
        print("Result: STRING REJECTED")


# Execute NFA
nfa_simulation()

# DFA to NFA Conversion
# A DFA is a special case of an NFA.
# Each DFA transition is converted into
# an NFA transition containing one destination state.

def dfa_to_nfa():

    print("===== DFA TO NFA CONVERSION =====")

    # States
    states = ['q0', 'q1']

    # Alphabet
    alphabet = ['0', '1']

    # DFA transition table
    dfa_transitions = {
        'q0': {
            '0': 'q0',
            '1': 'q1'
        },
        'q1': {
            '0': 'q0',
            '1': 'q1'
        }
    }

    # Start state
    start_state = 'q0'

    # Final state
    final_states = {'q1'}

    print("\n===== DFA TRANSITION TABLE =====")

    print("State\t0\t1")

    for state in states:
        print(
            f"{state}\t"
            f"{dfa_transitions[state]['0']}\t"
            f"{dfa_transitions[state]['1']}"
        )

    # Convert DFA transitions to NFA transitions
    nfa_transitions = {}

    for state in states:

        nfa_transitions[state] = {}

        for symbol in alphabet:

            destination = dfa_transitions[state][symbol]

            # NFA transition contains destination
            # inside a set
            nfa_transitions[state][symbol] = {destination}

    print("\n===== EQUIVALENT NFA TRANSITION TABLE =====")

    print("State\t0\t1")

    for state in states:

        print(
            f"{state}\t"
            f"{nfa_transitions[state]['0']}\t"
            f"{nfa_transitions[state]['1']}"
        )

    print("\n===== AUTOMATON DETAILS =====")
    print("States:", states)
    print("Alphabet:", alphabet)
    print("Start state:", start_state)
    print("Final states:", final_states)

    print("\nConversion completed successfully!")
    print("DFA and NFA are equivalent.")


# Execute conversion
dfa_to_nfa()
